.github/workflows/deploy.yml, src/main/java/com/beginvegan/domain/bookmark/application/BookmarkService.java, src/main/java/com/beginvegan/domain/bookmark/domain/repository/BookmarkRepository.java, src/main/java/com/beginvegan/domain/bookmark/domain/repository/ContentType.java, src/main/java/com/beginvegan/domain/food/application/FoodService.java, src/main/java/com/beginvegan/domain/food/domain/Food.java, src/main/java/com/beginvegan/domain/image/domain/Image.java, src/main/java/com/beginvegan/domain/image/domain/repository/ImageRepository.java, src/main/java/com/beginvegan/domain/magazine/application/MagazineService.java, src/main/java/com/beginvegan/domain/magazine/domain/Magazine.java, src/main/java/com/beginvegan/domain/magazine/domain/MagazineType.java, src/main/java/com/beginvegan/domain/magazine/domain/repository/MagazineRepository.java, src/main/java/com/beginvegan/domain/recommendation/domain/Recommendation.java, src/main/java/com/beginvegan/domain/recommendation/domain/repository/RecommendationRepository.java, src/main/java/com/beginvegan/domain/report/domain/Report.java, src/main/java/com/beginvegan/domain/report/domain/repository/ReportRepository.java, src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/domain/Restaurant.java, src/main/java/com/beginvegan/domain/restaurant/dto/MenuDetailRes.java, src/main/java/com/beginvegan/domain/restaurant/dto/RestaurantDetailRes.java, src/main/java/com/beginvegan/domain/review/domain/Review.java, src/main/java/com/beginvegan/domain/user/domain/User.java
> 내용을 적어주세요.
- ERD 변경사항 반영
- 엔티티 재구성
> 코멘트를 작성해주세요.
-  변경 사항으로 인해 일부 service 메소드를 주석 처리 했습니다. 구현 시 참고하면 될 듯 합니다.
- 추가로 이상 있으면 논의하거나 바꿔주시면 되겠습니다.
- 현재 database.yml create입니다
closes #3
=> [FEAT]: ERD 변경사항 반영

src/main/java/com/beginvegan/domain/bookmark/application/BookmarkService.java, src/main/java/com/beginvegan/domain/bookmark/domain/Bookmark.java, src/main/java/com/beginvegan/domain/bookmark/domain/repository/BookmarkRepository.java, src/main/java/com/beginvegan/domain/bookmark/dto/BookmarkListRes.java, src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/AroundRestaurantListRes.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/MenuDetailRes.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/RandomRestaurantRes.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/RestaurantAndMenusRes.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/RestaurantDetailRes.java, src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java, src/main/java/com/beginvegan/domain/review/application/ReviewService.java, src/main/java/com/beginvegan/domain/review/dto/ReviewDetailRes.java, src/main/java/com/beginvegan/domain/user/application/UserService.java
> 내용을 적어주세요.
- 홈화면에서 사용될 식당 3개 랜덤 조회
- 식당 3개 랜덤 조회 (북마크 여부 포함) 
> 코멘트를 작성해주세요.
-  변경사항이 많은 것 같지만 디렉토리 변경 때문에 그런 것 같습니다.
- bookmark 엔티티에 컬럼이 빠져 있길래 컬럼 추가를 했습니다.
- 지라 이슈 단위로 pr 올릴지 .. 고민이 되는데(이렇게 하면 pr이 너무 많아지므로) 일단 올리겠습니다..
closes #11
=> [FEAT]: 홈화면 - 식당 3개 랜덤 조회

src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/dto/request/LocationReq.java, src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java
> 내용을 적어주세요.
- 권한 동의 여부에 따라 홈화면에 노출될 레스토랑이 다릅니다
- 권한 동의 시 근처 식당 조회
> 코멘트를 작성해주세요.
-  LocationReq에서 id 뺐습니다
https://begin-vegan.atlassian.net/jira/software/c/projects/BVVER24/boards/5/timeline?selectedIssue=BVVER24-65
closes #15
=> [FEAT]: 권한 동의 시 근처 식당 랜덤 조회

src/main/java/com/beginvegan/domain/image/domain/repository/ImageRepository.java, src/main/java/com/beginvegan/domain/recommendation/domain/repository/RecommendationRepository.java, src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/domain/RestaurantType.java, src/main/java/com/beginvegan/domain/restaurant/domain/repository/RestaurantRepository.java, src/main/java/com/beginvegan/domain/restaurant/dto/request/RestaurantDetailReq.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/MenuDetailRes.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/RestaurantBannerRes.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/RestaurantDetailRes.java, src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java, src/main/java/com/beginvegan/domain/review/domain/repository/ReviewRepository.java, src/main/java/com/beginvegan/domain/review/dto/RestaurantReviewDetailRes.java, src/main/java/com/beginvegan/domain/user/dto/UserRestaurantDetailRes.java
> 내용을 적어주세요.
- 가까운 식당 리스트 & 식당 상세 조회(메뉴, 리뷰 포함)
- 가까운 식당 리스트 (가까운순 정렬 / 페이징)
- 식당 상세 조회(메뉴, 리뷰 포함)
가까운 식당 리스트
식당 상세 조회(메뉴, 리뷰 포함)
> 코멘트를 작성해주세요.
-  얽혀 있는 것이 많아 코드가 길어요 흐름 파악만 하면 이해하는 것에는 문제가 없어 보입니다.
- 식당 상세 조회 시 리뷰 필터 정렬에 관하여 일단 String으로 했고, 좀 더 생각해보고 변경 시 FIX로 올리겠습니다
closes #17
=> [FEAT]: 가까운 식당 리스트 & 식당 상세 조회(메뉴, 리뷰 포함)

src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/domain/Restaurant.java, src/main/java/com/beginvegan/domain/restaurant/domain/repository/RestaurantRepository.java, src/main/java/com/beginvegan/domain/restaurant/dto/request/SearchRestaurantReq.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/SearchRestaurantWithSortRes.java, src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/dto/UserRestaurantDetailRes.java
> 내용을 적어주세요.
- 식당 검색 + 정렬 + 페이징
- 식당 검색 + 정렬 + 페이징
> 코멘트를 작성해주세요.
- 안드로이드, 기획 분들과 논의 후 검색 조건이 상당히 까다로워서 1차적으로 완료하고 다른 것 먼저 구현하기로 했습니다.
- 특히, 검색 repository 부분 코드가 상당히 더러운데, 저도 이해가 잘 안되지만, 간략히 설명하자면 현재 상태는 딱 맞는 단어가 나오면 검색할 수 있습니다. 예를 들면, "강남"이면 되는데, "강남 식당" 이런거 안되고, "강남머시기" 이런거 안되는 상황입니다.
- 추가 논의 후 검색에 관한 부분 기획 수정 혹은 클라이언트와의 협업으로 보완할 예정입니다.
cleses #21
=> [FEAT]: map 내 식당 검색 + 정렬

src/main/java/com/beginvegan/domain/bookmark/application/BookmarkService.java, src/main/java/com/beginvegan/domain/bookmark/domain/repository/BookmarkRepository.java, src/main/java/com/beginvegan/domain/bookmark/dto/request/BookmarkReq.java, src/main/java/com/beginvegan/domain/bookmark/dto/response/BookmarkListRes.java, src/main/java/com/beginvegan/domain/bookmark/presentation/BookmarkController.java, src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/BookmarkRestaurantRes.java
> 내용을 적어주세요.
- 식당 / 매거진 / 레시피 스크랩 및 스크랩 해제 && 스크랩 한 식당 조회
- 식당 / 매거진 / 레시피 스크랩 
- 식당 / 매거진 / 레시피 스크랩 해제
- 스크랩 한 식당 조회
> 코멘트를 작성해주세요.
-  하나의 API로 식당 / 매거진 / 레시피 스크랩 관리하는 것보다 나누는 것이 좋아보여 나눴습니다.
=> [FEAT]: 식당 / 매거진 / 레시피 스크랩 및 스크랩 해제 && 스크랩 한 식당 조회

src/main/java/com/beginvegan/domain/bookmark/application/BookmarkService.java, src/main/java/com/beginvegan/domain/bookmark/presentation/BookmarkController.java, src/main/java/com/beginvegan/domain/food/application/FoodService.java, src/main/java/com/beginvegan/domain/food/dto/response/BookmarkFoodRes.java
> 내용을 적어주세요.
- 스크랩한 레시피 목록 조회
- 마이페이지: 스크랩한 레시피 목록 조회
> 코멘트를 작성해주세요.
-  스크랩한 레시피 목록 조회입니다. 마이 페이지에서 확인 가능합니다.
closes #25
=> [Feat]: 스크랩한 레시피 목록 조회

src/main/java/com/beginvegan/domain/bookmark/application/BookmarkService.java, src/main/java/com/beginvegan/domain/bookmark/domain/repository/BookmarkRepository.java, src/main/java/com/beginvegan/domain/bookmark/presentation/BookmarkController.java, src/main/java/com/beginvegan/domain/magazine/application/MagazineService.java, src/main/java/com/beginvegan/domain/magazine/dto/response/BookmarkMagazineRes.java
> 내용을 적어주세요.
- 스크랩한 매거진 목록 조회
- 스크랩한 매거진 목록 조회
- 스크랩 목록 조회 전체 페이징 처리
> 코멘트를 작성해주세요.
- 무한 스크롤인데, 페이징 처리를 빼먹어서 추가했습니다.
- 페이징 처리에 관해서 클라이언트 측과 논의하여 추가할 사항이 있다면 추가하겠습니다.
- 최신순 정렬입니다.
closes #26
=> [FEAT]: 스크랩한 매거진 목록 조회

src/main/java/com/beginvegan/domain/suggestion/application/ModificationSuggestionService.java, src/main/java/com/beginvegan/domain/suggestion/application/RegistrationSuggestionService.java, src/main/java/com/beginvegan/domain/suggestion/domain/child/ModificationSuggestion.java, src/main/java/com/beginvegan/domain/suggestion/domain/child/RegistrationSuggestion.java, src/main/java/com/beginvegan/domain/suggestion/domain/child/repository/ModificationSuggestionRepository.java, src/main/java/com/beginvegan/domain/suggestion/domain/child/repository/RegistrationSuggestionRepository.java, src/main/java/com/beginvegan/domain/suggestion/domain/parent/Suggestion.java, src/main/java/com/beginvegan/domain/suggestion/domain/parent/repository/ModificationSuggestionRepository.java, src/main/java/com/beginvegan/domain/suggestion/dto/request/ModifyReq.java, src/main/java/com/beginvegan/domain/suggestion/dto/request/RegistReq.java, src/main/java/com/beginvegan/domain/suggestion/presentation/ModificationSuggestionController.java, src/main/java/com/beginvegan/domain/suggestion/presentation/RegistrationSuggestionController.java
> 내용을 적어주세요.
- 식당 정보 수정 제보 
- 기존 식당 정보 수정 제보
- 식당 정보 수정 제보 
- 기존 식당 정보 수정 제보
> 코멘트를 작성해주세요.
-  어드민이 관리할 유저로부터 받는 식당 관련 내용들입니다.
closes #27
=> [FEAT]: 식당 정보 수정 제보 && 기존 식당 정보 수정 제보

src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java
> 내용을 적어주세요.
- 10km 내 식당 없을 시 무한 로딩 해결
- 10km 내 식당 없을 시 무한 로딩 해결
> 코멘트를 작성해주세요.
-  10km 내 식당 없을 시 Set에서 수를 넣는 행위가 무한 지속되는 문제 해결
=> [FIX]: 10km 내 식당 없을 시 무한 로딩 해결

src/main/java/com/beginvegan/BeginVeganApplication.java, src/main/java/com/beginvegan/domain/recommendation/domain/repository/RecommendationRepository.java, src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/domain/Restaurant.java, src/main/java/com/beginvegan/domain/restaurant/dto/request/RestaurantDetailReq.java, src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java, src/main/java/com/beginvegan/domain/review/application/ReviewService.java, src/main/java/com/beginvegan/domain/review/domain/Review.java, src/main/java/com/beginvegan/domain/review/domain/repository/ReviewRepository.java, src/main/java/com/beginvegan/domain/review/dto/PostReviewReq.java, src/main/java/com/beginvegan/domain/review/dto/RestaurantInfoRes.java, src/main/java/com/beginvegan/domain/review/dto/request/PostReviewReq.java, src/main/java/com/beginvegan/domain/review/dto/request/UpdateReviewReq.java, src/main/java/com/beginvegan/domain/review/dto/response/RecommendationByUserAndReviewRes.java, src/main/java/com/beginvegan/domain/review/dto/response/RestaurantInfoRes.java, src/main/java/com/beginvegan/domain/review/dto/response/RestaurantReviewDetailRes.java, src/main/java/com/beginvegan/domain/review/dto/response/ReviewDetailRes.java, src/main/java/com/beginvegan/domain/review/dto/response/ReviewListRes.java, src/main/java/com/beginvegan/domain/review/presentation/ReviewController.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/domain/User.java, src/main/java/com/beginvegan/domain/user/dto/UpdateAlarmSettingRes.java, src/main/java/com/beginvegan/domain/user/presentation/UserController.java
> 내용을 적어주세요.
- 리뷰 작성 및 수정, 삭제 등 전반적인 리뷰 관련 기능 구현
- 리뷰 작성 시 식당 정보 조회
- 리뷰 작성
- 리뷰 추천
- 포토 리뷰 필터
- 리뷰 수정
- 리뷰 수정 시 기존 리뷰 내용 불러오기
- 리뷰 삭제
- 매일 00시 식당 평점 업데이트
> 코멘트를 작성해주세요.
- 검증된 리뷰 삭제시 리워드 회수하도록 구현
- 식당 리뷰 조회 기능에서 포토리뷰 필터 추가했습니다
- 기획 파트에 여쭤봐야 할 내용이 몇 가지 있어 해당 부분 답변받고 추가로 수정할 예정입니다!
closes #22
=> [FEAT]: 리뷰 작성 및 관련 기능 구현

src/main/java/com/beginvegan/domain/auth/application/CustomDefaultOAuth2UserService.java, src/main/java/com/beginvegan/domain/auth/presentation/AuthController.java, src/main/java/com/beginvegan/domain/recommendation/domain/Recommendation.java, src/main/java/com/beginvegan/domain/recommendation/domain/repository/RecommendationRepository.java, src/main/java/com/beginvegan/domain/report/domain/Report.java, src/main/java/com/beginvegan/domain/report/dto/ReportContentReq.java, src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/review/application/ReviewService.java, src/main/java/com/beginvegan/domain/review/domain/Review.java, src/main/java/com/beginvegan/domain/review/domain/repository/ReviewRepository.java, src/main/java/com/beginvegan/domain/review/dto/response/MyReviewRes.java, src/main/java/com/beginvegan/domain/review/presentation/ReviewController.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/presentation/UserController.java
> 내용을 적어주세요.
- 리뷰 신고 기능 구현
- 리뷰 신고 
> 코멘트를 작성해주세요.
- 답변받은 사항 반영하여 리뷰 추천 기능 로직 수정했습니다
- Report 엔티티 컬럼 수정 있습니다(`content` 컬럼 추가)
- 리뷰 신고 -> 관리자가 리뷰를 삭제할 경우 `visible = false`로 변경해주세요!  
- 사용자의 재추천 여부를 확인하기 위해 `Recommendation` 데이터 **soft delete**로 변경했습니다! 이에 따라 식당 리뷰 조회-추천 수를 Status가 ACTIVE인 것만 가져오도록 수정했습니다. 
- _나의 리뷰 조회는 디자인 수정되면 추가로 구현해서 PR 올려두겠습니다_
closes #36
=> [FEAT]: 리뷰 신고

src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/auth/application/CustomDefaultOAuth2UserService.java, src/main/java/com/beginvegan/domain/review/application/ReviewService.java, src/main/java/com/beginvegan/domain/review/domain/Review.java, src/main/java/com/beginvegan/domain/review/presentation/ReviewController.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/domain/User.java, src/main/java/com/beginvegan/domain/user/dto/MyPageUserInfoRes.java, src/main/java/com/beginvegan/domain/user/presentation/UserController.java
> 내용을 적어주세요.
- 회원 탈퇴 기능 구현
- 회원 탈퇴(Soft Delete)
> 코멘트를 작성해주세요.
- 회원이 탈퇴해도 작성한 리뷰는 남아있어야 하므로 **soft delete**로 구현했습니다
- 개인정보 관련하여 고민을 좀 해봤는데, 아예 복구 불가능하게 변경해야 하므로 해시함수 사용했습니다
(참고: https://velog.io/@postlist/JAVA-SHA-256-%EC%95%94%ED%98%B8%ED%99%94-salt-%EC%82%AC%EC%9A%A9)
데이터 참고:
- 요구사항: 탈퇴 후 재가입 가능 -> 재가입 되는 것 확인했습니다!
closes #41 
++ 추가로, 리뷰 삭제 시 연관된 `Recommendation`, `Report` 데이터도 삭제해야 하므로 `CASCADE.REMOVE` 설정 추가했습니다
=> [FEAT]: 회원 탈퇴

src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/auth/application/CustomDefaultOAuth2UserService.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/domain/User.java, src/main/java/com/beginvegan/domain/user/dto/MyPageUserInfoRes.java
> 내용을 적어주세요.
- 회원가입, 로그인 등 auth 관련 로직 수정
- 회원가입 변경
- 로그인 변경
> 코멘트를 작성해주세요.
-  `user`엔티티 컬럼 추가했습니다!
closes #48
=> [FEAT] Auth 관련 수정

src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/auth/dto/SignInRes.java
> 내용을 적어주세요.
- 로그인 응답 값 수정
- 로그인 시 `signUpCompleted` 컬럼 응답 추가
> 코멘트를 작성해주세요.
-  로그인 시 추가정보 입력 여부가 필요하므로 응답 값에 추가했습니다!
=> [REFACTOR] 로그인 시 응답 값 추가

src/main/java/com/beginvegan/domain/magazine/application/MagazineService.java, src/main/java/com/beginvegan/domain/magazine/domain/Magazine.java, src/main/java/com/beginvegan/domain/magazine/dto/response/MagazineDetailRes.java, src/main/java/com/beginvegan/domain/magazine/dto/response/MagazineListRes.java, src/main/java/com/beginvegan/domain/magazine/presentation/MagazineController.java, src/main/java/com/beginvegan/domain/restaurant/domain/Restaurant.java
> 내용을 적어주세요.
- 매거진 조회 관련 기능 구현
- 매거진 리스트 조회(+페이징)
- 메거진 상세조회
- 매거진 랜덤 3개 조회
> 코멘트를 작성해주세요.
-
=> [FEAT]: 매거진 조회 관련 기능 구현

src/main/java/com/beginvegan/domain/review/application/ReviewService.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/presentation/UserController.java
> 내용을 적어주세요.
- 포토리뷰 검수 자동화
- 기존 리뷰 등록 API에 포토리뷰일 경우 자동 검수 후 리워드 지급
> 코멘트를 작성해주세요.
-  
closes #47
=> [FEAT]: 포토리뷰 리워드 지급 자동화

src/main/java/com/beginvegan/domain/magazine/application/MagazineService.java
> 내용을 적어주세요.
- 매거진 썸네일 response 누락 수정
- 
> 코멘트를 작성해주세요.
-
=> [FIX]: 매거진 썸네일 response 누락 수정

src/main/java/com/beginvegan/domain/food/application/FoodService.java, src/main/java/com/beginvegan/domain/food/domain/repository/FoodRepository.java, src/main/java/com/beginvegan/domain/food/presentation/FoodController.java, src/main/java/com/beginvegan/domain/user/domain/VeganType.java
> 내용을 적어주세요.
- 나를 위한 레시피 기능 구현
- 나를 위한 레시피 기능 구현
> 코멘트를 작성해주세요.
-
=> [FEAT]: 나를 위한 레시피 기능 구현

src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/auth/application/CustomDefaultOAuth2UserService.java, src/main/java/com/beginvegan/domain/auth/dto/AddUserInfoReq.java, src/main/java/com/beginvegan/domain/auth/dto/SignUpReq.java, src/main/java/com/beginvegan/domain/auth/presentation/AuthController.java, src/main/java/com/beginvegan/domain/user/domain/User.java
> 내용을 적어주세요.
- 회원가입 관련 API 수정
- 회원가입 구현, 추가 정보 입력 API 수정
> 코멘트를 작성해주세요.
- 회원가입 API 구현: email과 providerId를 받는 회원가입 기능 구현
- 추가 정보 입력 API 수정: http 메소드 변경 및 requestDto명 변경
=> [FEAT] 회원가입 기능 추가 구현

.github/workflows/deploy.yml, .gitignore, build.gradle, src/main/java/com/beginvegan/BeginVeganApplication.java, src/main/java/com/beginvegan/domain/alarm/application/AlarmService.java, src/main/java/com/beginvegan/domain/alarm/domain/Alarm.java, src/main/java/com/beginvegan/domain/alarm/domain/AlarmType.java, src/main/java/com/beginvegan/domain/alarm/domain/repository/AlarmRepository.java, src/main/java/com/beginvegan/domain/alarm/dto/AlarmHistoryRes.java, src/main/java/com/beginvegan/domain/alarm/dto/ReadAlarmRes.java, src/main/java/com/beginvegan/domain/alarm/dto/UnreadAlarmRes.java, src/main/java/com/beginvegan/domain/alarm/presentation/AlarmController.java, src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/auth/presentation/AuthController.java, src/main/java/com/beginvegan/domain/fcm/application/FcmService.java, src/main/java/com/beginvegan/domain/fcm/dto/FcmMessageDto.java, src/main/java/com/beginvegan/domain/fcm/dto/FcmSendDto.java, src/main/java/com/beginvegan/domain/fcm/presentation/FcmController.java, src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/review/application/ReviewService.java, src/main/java/com/beginvegan/domain/review/presentation/ReviewController.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/domain/User.java, src/main/java/com/beginvegan/domain/user/domain/UserLevel.java, src/main/java/com/beginvegan/domain/user/domain/repository/UserRepository.java, src/main/java/com/beginvegan/domain/user/dto/UpdateFcmTokenReq.java, src/main/java/com/beginvegan/domain/user/presentation/UserController.java, src/main/java/com/beginvegan/global/config/security/SecurityConfig.java
> 내용을 적어주세요.
- FCM, 알림 내역 관련 기능 구현
- FCM 토큰 업데이트
- FCM 전송
- 알림 내역 조회
- 알림 상태 변경
> 코멘트를 작성해주세요.
- `user` 테이블에 `fcmToken`, `userLevel` 추가했습니다
- `userLevel` 추가됨으로써 기존 userLevel 응답 반환 로직 수정(restaurant, user쪽)
- 서버에서 실제 푸시알림이 가는지 확인하지 못해서, 포스트맨 응답이 제대로 가는지, 알림이 저장되는지 위주로 확인했습니다
- firebase관련 파일 추가되었습니다!(yml, json)
=> [FEAT]: 알림 기능 구현

.github/workflows/deploy.yml
> 내용을 적어주세요.
- 
- 
> 코멘트를 작성해주세요.
-
=> [CHORE]: deploy yml

src/main/java/com/beginvegan/domain/bookmark/domain/repository/BookmarkRepository.java, src/main/java/com/beginvegan/domain/food/application/FoodService.java, src/main/java/com/beginvegan/domain/food/dto/response/FoodDetailRes.java, src/main/java/com/beginvegan/domain/food/dto/response/FoodListRes.java, src/main/java/com/beginvegan/domain/food/dto/response/FoodRecipeListRes.java, src/main/java/com/beginvegan/domain/food/presentation/FoodController.java, src/main/java/com/beginvegan/domain/magazine/application/MagazineService.java, src/main/java/com/beginvegan/domain/magazine/dto/response/MagazineDetailRes.java, src/main/java/com/beginvegan/domain/magazine/dto/response/MagazineListRes.java, src/main/java/com/beginvegan/domain/magazine/presentation/MagazineController.java
> 내용을 적어주세요.
- magazine, recipe 북마크 조회 여부 추가
-  magazine, recipe 북마크 조회 여부 추가
- 작성자 정보 및 생성일 조회 추가
> 코멘트를 작성해주세요.
-  북마크 여부 조회의 경우 따로 private 메소드 추가해서 분리했습니다.
=> [FIX] magazine, recipe 북마크 조회 여부 추가

src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/auth/application/CustomDefaultOAuth2UserService.java
> 내용을 적어주세요.
- 소셜 로그인 및 로그인 시 예외처리 추가
- **추가 정보 입력**을 진행하지 않은 경우 소셜로그인, 로그인 API에서 예외처리를 반환합니다. 
> 코멘트를 작성해주세요.
-
=> [FIX]: 로그인 예외처리 추가

src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/auth/application/CustomDefaultOAuth2UserService.java, src/main/java/com/beginvegan/domain/auth/presentation/AuthController.java, src/main/java/com/beginvegan/domain/fcm/application/FcmService.java
> 내용을 적어주세요.
- 로그인, 회원가입 통합
- 로그인 API
- 비회원: 회원가입 후 로그인, 토큰 발급
- 회원: 로그인 후 토큰 발급
> 코멘트를 작성해주세요.
-  fcm 쪽에 바뀐 로직이 있는데, user 데이터에 fcm 토큰이 없을 경우 오류가 발생하는 api(추가정보입력)가 있어 수정했습니다
=> [FIX]: 로그인 및 회원가입 통합

src/main/java/com/beginvegan/domain/food/application/FoodService.java
> 내용을 적어주세요.
- 나를 위한 레시피 로직 수정
- 나를 위한 레시피 로직이 아예 반대로 되어있어서 수정했습니다!
> 코멘트를 작성해주세요.
-
=> [FIX]: 나를 위한 레시피 로직 수정

src/main/java/com/beginvegan/domain/bookmark/application/BookmarkService.java, src/main/java/com/beginvegan/domain/bookmark/presentation/BookmarkController.java, src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/dto/request/LocationReq.java, src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java
> 내용을 적어주세요.
- GET request boddy -> request param
- restaurant / bookmark
> 코멘트를 작성해주세요.
-
=> [FIX]: request boddy -> request param

src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/RandomRestaurantRes.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/RestaurantBannerRes.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/SearchRestaurantWithSortRes.java
> 내용을 적어주세요.
- 응답에 식당 위치 추가
- map에서 지도에 식당 찍기 위함
> 코멘트를 작성해주세요.
-
=> [FIX]: 응답에 식당 위치 추가

src/main/java/com/beginvegan/domain/restaurant/domain/repository/RestaurantRepository.java
> 내용을 적어주세요.
- 
- 
> 코멘트를 작성해주세요.
-
=> [FIX]: solve Restaurant doesn't exist

src/main/java/com/beginvegan/domain/restaurant/domain/RestaurantType.java
>  레스토랑 타입 필드 enum 타입 추가
- 
- KOREAN(한식), JAPANESE(일식) 추가
> 코멘트를 작성해주세요.
-
=> [FIX]: 레스토랑 enum 타입 추가

src/main/java/com/beginvegan/domain/user/dto/UpdateFcmTokenReq.java
> 내용을 적어주세요.
- 오류 수정을 위해 @NoArgsConstructor 추가
- UpdateFcmTokenReq에 @NoArgsConstructor 추가
> 코멘트를 작성해주세요.
=> [FIX]:  JSON 파싱 오류 수정

src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/dto/response/RestaurantDetailRes.java
> 내용을 적어주세요.
- 
- 
> 코멘트를 작성해주세요.
-
=> [FIX]: 식당 상세 조회 이미지 추가

src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/fcm/application/FcmService.java, src/main/java/com/beginvegan/domain/fcm/domain/MessageType.java, src/main/java/com/beginvegan/domain/fcm/dto/FcmMessageDto.java, src/main/java/com/beginvegan/domain/fcm/dto/FcmSendDto.java, src/main/java/com/beginvegan/domain/review/application/ReviewService.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/dto/UpdateFcmTokenReq.java
> 내용을 적어주세요.
- fcm push type인 notification과 data 병합
- notification과 data 병합으로 fcmSendDto 컬럼 추가 및 전달 데이터 소폭 변경
- UpdateFcmTokenReq의 json parsing 에러 수정
> 코멘트를 작성해주세요.
-
=> [FEAT] FCM Push 방식 병합

src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java, src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java
> 내용을 적어주세요.
- 리뷰 조회 시 요청 파라미터 값 수정
- 
> 코멘트를 작성해주세요.
-
=> [FIX]: 식당 리뷰 조회 요청 값 수정

src/main/java/com/beginvegan/domain/fcm/application/FcmService.java, src/main/java/com/beginvegan/domain/fcm/dto/FcmSendDto.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/dto/StoredFcmTokenRes.java, src/main/java/com/beginvegan/domain/user/presentation/UserController.java
> 내용을 적어주세요.
- 사용자의 FCM 토큰 저장 여부 구현 및 FCM 요청 값 변경
- FCM 토큰 저장 여부 구현
- FCM 요청 값 fcmToken에서 userId로 변경
> 코멘트를 작성해주세요.
-  fcmToken은 서버에 저장 후 클라이언트 쪽에서 확인할 수 있는 방법이 없다고 합니다! 따라서 fcm 메세지 요청 시 fcmToken을 받는 것이 아니라 userId를 받는 것으로 변경했습니다
=> [FEAT]: 사용자의 FCM 토큰 저장 여부 구현

src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/fcm/application/FcmService.java, src/main/java/com/beginvegan/domain/fcm/dto/FcmSendDto.java, src/main/java/com/beginvegan/domain/review/application/ReviewService.java, src/main/java/com/beginvegan/domain/user/application/UserService.java
> 내용을 적어주세요.
- 기존 push 알림 요청 값 변경
- userId 에서 fcm token으로 변경
> 코멘트를 작성해주세요.
-
=> [REFACTOR]: 알림 요청값 FCM token으로 변경

src/main/java/com/beginvegan/domain/fcm/application/FcmService.java, src/main/java/com/beginvegan/domain/fcm/dto/FcmMessageDto.java, src/main/java/com/beginvegan/domain/fcm/presentation/FcmController.java
> 내용을 적어주세요.
- FCM API 응답 수정
- 오류 원인을 파악하기 위해 메세지 요청 시 오류가 있다면 오류를 반환하도록 응답을 수정했습니다
> 코멘트를 작성해주세요.
-
=> [REFACTOR]: FCM API 응답 수정

src/main/java/com/beginvegan/domain/fcm/application/FcmService.java
> 내용을 적어주세요.
- 요청 URL 변경
- Fcm 메세지 요청 시 URL 주소 변경
> 코멘트를 작성해주세요.
-
=> [REFACTOR]: FCM 요청 URL 변경

src/main/java/com/beginvegan/domain/fcm/application/FcmInitializer.java, src/main/java/com/beginvegan/domain/fcm/application/FcmService.java, src/main/java/com/beginvegan/domain/fcm/exception/FcmMessageException.java
> 내용을 적어주세요.
- fcm 오류 원인 파악을 위해 토큰의 유효성을 검증
- 토큰 유효성 검증 및 서버 실행 시 FCM 초기화
> 코멘트를 작성해주세요.
-
=> [FEAT]: FCM 토큰 유효성 검증

src/main/java/com/beginvegan/domain/fcm/application/FcmService.java
> 내용을 적어주세요.
- 
- 
> 코멘트를 작성해주세요.
-
=> [FIX]: FCM 테스트 발송 로직 삭제

src/main/java/com/beginvegan/domain/auth/application/AuthService.java, src/main/java/com/beginvegan/domain/auth/presentation/AuthController.java, src/main/java/com/beginvegan/domain/fcm/application/FcmService.java, src/main/java/com/beginvegan/domain/fcm/presentation/FcmController.java, src/main/java/com/beginvegan/domain/review/application/ReviewService.java, src/main/java/com/beginvegan/domain/review/presentation/ReviewController.java, src/main/java/com/beginvegan/domain/user/application/UserService.java, src/main/java/com/beginvegan/domain/user/presentation/UserController.java
> 내용을 적어주세요.
- FCM 호출 및 구현 방식 변경
- http 호출에서 Firebase Admin SDK를 사용하도록 변경
> 코멘트를 작성해주세요.
-
=> [FIX]: FCM 구현 방식 변경
